import type { CityData } from "@/components/city-card";

// Mock data for cities
export const cities: CityData[] = [
  {
    rank: 1,
    slug: "seoul-gangnam",
    name: "서울 강남구",
    nameEn: "Seoul, Gangnam",
    image: "https://images.unsplash.com/photo-1538485399081-7191377e8241?w=800&q=80",
    internetSpeed: 832,
    temperature: 12,
    monthlyCost: 1850000,
    rating: 4.7,
    reviewCount: 312,
    cafeCount: 156,
    coworkingCount: 23,
    transport: "excellent",
    description: "한국의 비즈니스 중심지이자 디지털 노마드의 천국",
    longDescription: "서울 강남구는 대한민국의 경제·문화·IT 중심지로, 세계 최고 수준의 인터넷 인프라와 다양한 코워킹 스페이스를 갖추고 있습니다. 24시간 운영되는 카페와 레스토랑, 편리한 대중교통으로 디지털 노마드에게 최적의 환경을 제공합니다.",
    location: { country: "대한민국", region: "서울특별시" },
    images: [
      "https://images.unsplash.com/photo-1538485399081-7191377e8241?w=800&q=80",
      "https://images.unsplash.com/photo-1601376192647-3c7cdad24328?w=800&q=80",
    ],
    amenities: {
      wifi: "평균 832Mbps의 초고속 인터넷",
      cafes: "156개의 노마드 친화적 카페",
      coworking: "23개의 프리미엄 코워킹 스페이스",
      cost: "월 평균 185만원의 생활비",
    },
  },
  {
    rank: 2,
    slug: "jeju-seogwipo",
    name: "제주 서귀포",
    nameEn: "Jeju, Seogwipo",
    image: "https://images.unsplash.com/photo-1579169825453-7f5f4f3c3e3c?w=800&q=80",
    internetSpeed: 245,
    temperature: 15,
    monthlyCost: 1200000,
    rating: 4.9,
    reviewCount: 189,
    cafeCount: 89,
    coworkingCount: 7,
    transport: "average",
    description: "자연과 함께하는 워케이션의 성지",
    longDescription: "제주 서귀포는 아름다운 자연경관과 온화한 기후로 유명한 워케이션 최적지입니다. 해변과 오름, 폭포가 어우러진 환경에서 일과 휴식의 완벽한 균형을 찾을 수 있습니다.",
    location: { country: "대한민국", region: "제주특별자치도" },
    images: [
      "https://images.unsplash.com/photo-1579169825453-7f5f4f3c3e3c?w=800&q=80",
    ],
    amenities: {
      wifi: "평균 245Mbps의 안정적인 인터넷",
      cafes: "89개의 오션뷰 카페",
      coworking: "7개의 자연 친화적 코워킹 스페이스",
      cost: "월 평균 120만원의 생활비",
    },
  },
  {
    rank: 3,
    slug: "busan-haeundae",
    name: "부산 해운대",
    nameEn: "Busan, Haeundae",
    image: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800&q=80",
    internetSpeed: 512,
    temperature: 14,
    monthlyCost: 1350000,
    rating: 4.6,
    reviewCount: 245,
    cafeCount: 112,
    coworkingCount: 15,
    transport: "good",
    description: "해변과 도시가 공존하는 항구도시",
    longDescription: "부산 해운대는 대한민국 제2의 도시 부산의 대표적인 관광지이자 비즈니스 중심지입니다. 해변을 따라 늘어선 카페와 코워킹 스페이스에서 바다를 바라보며 일할 수 있습니다.",
    location: { country: "대한민국", region: "부산광역시" },
    images: [
      "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800&q=80",
    ],
    amenities: {
      wifi: "평균 512Mbps의 빠른 인터넷",
      cafes: "112개의 해변 카페",
      coworking: "15개의 현대적인 코워킹 스페이스",
      cost: "월 평균 135만원의 생활비",
    },
  },
  {
    rank: 4,
    slug: "gangneung",
    name: "강릉시",
    nameEn: "Gangneung",
    image: "https://images.unsplash.com/photo-1569074187119-c87815b476da?w=800&q=80",
    internetSpeed: 312,
    temperature: 10,
    monthlyCost: 950000,
    rating: 4.5,
    reviewCount: 156,
    cafeCount: 67,
    coworkingCount: 5,
    transport: "average",
    description: "커피와 바다의 도시",
    longDescription: "강릉은 대한민국의 커피 문화를 선도하는 도시로, 동해안의 아름다운 해변과 함께 독특한 카페 문화를 자랑합니다. 조용하고 여유로운 분위기에서 집중하며 일하기 좋습니다.",
    location: { country: "대한민국", region: "강원특별자치도" },
    images: [
      "https://images.unsplash.com/photo-1569074187119-c87815b476da?w=800&q=80",
    ],
    amenities: {
      wifi: "평균 312Mbps의 인터넷",
      cafes: "67개의 스페셜티 카페",
      coworking: "5개의 코워킹 스페이스",
      cost: "월 평균 95만원의 생활비",
    },
  },
  {
    rank: 5,
    slug: "jeonju-hanok",
    name: "전주 한옥마을",
    nameEn: "Jeonju, Hanok Village",
    image: "https://images.unsplash.com/photo-1534274867514-d5b47ef89ed7?w=800&q=80",
    internetSpeed: 287,
    temperature: 11,
    monthlyCost: 850000,
    rating: 4.4,
    reviewCount: 98,
    cafeCount: 54,
    coworkingCount: 4,
    transport: "good",
    description: "전통과 현대가 어우러진 문화도시",
    longDescription: "전주 한옥마을은 한국 전통문화의 중심지로, 한옥 카페와 현대적인 코워킹 스페이스가 조화를 이루는 독특한 도시입니다. 합리적인 생활비와 풍부한 먹거리로 장기 체류에 적합합니다.",
    location: { country: "대한민국", region: "전북특별자치도" },
    images: [
      "https://images.unsplash.com/photo-1534274867514-d5b47ef89ed7?w=800&q=80",
    ],
    amenities: {
      wifi: "평균 287Mbps의 인터넷",
      cafes: "54개의 한옥 카페",
      coworking: "4개의 코워킹 스페이스",
      cost: "월 평균 85만원의 생활비",
    },
  },
  {
    rank: 6,
    slug: "daejeon-yuseong",
    name: "대전 유성구",
    nameEn: "Daejeon, Yuseong",
    image: "https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=800&q=80",
    internetSpeed: 456,
    temperature: 13,
    monthlyCost: 900000,
    rating: 4.3,
    reviewCount: 67,
    cafeCount: 78,
    coworkingCount: 9,
    transport: "excellent",
    description: "대한민국의 과학기술 허브",
    longDescription: "대전 유성구는 대덕연구단지를 중심으로 한 과학기술 중심 도시입니다. 우수한 인터넷 인프라와 스타트업 친화적인 환경, 합리적인 생활비로 IT 노마드에게 이상적입니다.",
    location: { country: "대한민국", region: "대전광역시" },
    images: [
      "https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=800&q=80",
    ],
    amenities: {
      wifi: "평균 456Mbps의 빠른 인터넷",
      cafes: "78개의 테크 친화적 카페",
      coworking: "9개의 스타트업 코워킹 스페이스",
      cost: "월 평균 90만원의 생활비",
    },
  },
];

export function getCityBySlug(slug: string): CityData | undefined {
  return cities.find((city) => city.slug === slug);
}

export function getAllCities(): CityData[] {
  return cities;
}

export function getAllCitySlugs(): string[] {
  return cities.map((city) => city.slug);
}
